mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=fwwb_platform;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456

myoss:
  xxaccessKey: ty4AotBfLiTwbeEA3VhHpGTx7cqXhsgrlh1DvkXm
  xxsecretKey: 3ru3qjYHNBkOGJP-Mti-SCj7yEquaE8YrQOQC0Ps
  xxbucket: fwwb-source